# service node type, [DN|CN|LOG]
service-type = "LOG"
data-dir = "./mo-data"

[log]
level = "info"

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "SHARED"
backend = "DISK"
data-dir = "mo-data/s3"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[observability]
metricUpdateStorageUsageInterval = "15m"
enableStmtMerge = true
enableMetricToProm = true

[malloc]
check-fraction = 65536
enable-metrics = true
